name: Wakatime Charts

on:
    workflow_dispatch:
    schedule:
        - cron: "0 0 * * *"
    # branches:
    #     - main

jobs:
    update-charts:
        name: Update wakatime stats charts
        runs-on: ubuntu-latest
        steps:
            - uses: divykj/wakatime-charts@master
              with:
                  WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
                  BRANCH_NAME: main
                  #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # only required if using the action in repository other than profile
